// Generated by CoffeeScript 1.11.1
this.officetechhelp.lazy.controller('prodCtrl', function($rootScope, $scope, $stateParams) {
  var shuffle;
  $scope.restCards = [
    {
      'name': '1',
      'image': '1',
      'price': 1
    }, {
      'name': '2',
      'image': '2',
      'price': 2
    }, {
      'name': '3',
      'image': '3',
      'price': 3
    }, {
      'name': '4',
      'image': '4',
      'price': 4
    }, {
      'name': '5',
      'image': '5',
      'price': 3
    }, {
      'name': '6',
      'image': '6',
      'price': 3
    }, {
      'name': '7',
      'image': '7',
      'price': 7
    }, {
      'name': '8',
      'image': '8',
      'price': 8
    }, {
      'name': '9',
      'image': '9',
      'price': 9
    }
  ];
  $rootScope.cartdata = 0;
  $scope.addedCart = [];
  $scope.plist = $stateParams.productname;
  $scope.prodDesc = {
    'product': {
      'desc': 'Development of product.'
    },
    'html5': {
      'desc': 'Development of web pages using HTML coding.'
    },
    'seo': {
      'desc': 'online SEO & SEM development of web pages.'
    },
    'web-design': {
      'desc': 'Creative development of websites domains at affordable prices.'
    },
    'application': {
      'desc': 'Application development and support Android and IOS.'
    },
    'email-support': {
      'desc': 'Email client and support for corporate or home users.'
    }
  };
  $scope.description = $scope.prodDesc[$scope.plist].desc;
  $scope.addToCart = function(cart) {
    if ($.inArray(cart, $scope.addedCart) === -1) {
      $rootScope.cartdata = $rootScope.cartdata + 1;
      return $scope.addedCart.push(cart);
    }
  };
  $scope.chackCart = function(name) {
    return $.inArray(name, $scope.addedCart) > -1;
  };
  shuffle = function(array) {
    var currentIndex, randomIndex, temporaryValue;
    currentIndex = array.length;
    temporaryValue = void 0;
    randomIndex = void 0;
    while (0 !== currentIndex) {
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex -= 1;
      temporaryValue = array[currentIndex];
      array[currentIndex] = array[randomIndex];
      array[randomIndex] = temporaryValue;
    }
    array;
    return console.log(array);
  };
  return shuffle($scope.restCards);
});
